echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf d3blocks.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf d3blocks/__pycache__
rm -rf d3blocks/timeseries/__pycache__
rm -rf d3blocks/movingbubbles/__pycache__
rm -rf d3blocks/imageslider/__pycache__
rm -rf d3blocks/sankey/__pycache__
rm -rf d3blocks/scatter/__pycache__
rm -rf d3blocks/chord/__pycache__
rm -rf d3blocks/particles/__pycache__
rm -rf d3blocks/violin/__pycache__
rm -rf d3blocks/heatmap/__pycache__
rm -rf d3blocks/matrix/__pycache__
rm -rf d3blocks/treemap/__pycache__
rm -rf d3blocks/.pylint.d
rm -rf tests/__pycache__
rm -rf d3blocks/utils/__pycache__
rm -rf .pylint.d
rm -rf d3blocks/data/*.zip
rm -rf d3blocks/data/*.csv
rm -rf d3blocks/data/*.jpg
rm -rf d3blocks/d3blocks/*.html
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf .coverage*
rm -rf .pkl
rm -rf .ipynb_checkpoints